### ISSUE TITLE
Ta vekk oppføringer som har vært

### ISSUE THREAD

**Issue by oddlunde** [cybernetisk/internsystem-frontend#5]
Hei, 
Hadde vært greit å tatt vekk oppføringre som allerede har vært, som f.eks heile august:)

**Comment by thor** [comment]
Titten tei! Gjaldt dette hovedsakelig kalendermodulen? I så fall, er videreutvikling av den med tanke på normale arrangement nødvendig?

**Comment by henrist** [comment]
Det vi kanskje kunne gjort er å endret den slik at den henter data fra wiki og tilbyr et enklere API som kan brukes for offentlig kalender? Denne issuen er vel kun relevant hvis man beholder oversikten på internsia, men det er kanskje ikke nødvendig, eller?

**Comment by henrist** [comment]
Denne kalenderløsningen er aldri tatt helt i bruk og er faset ut til fordel for Confluence-løsningen. Lukker.
